# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Bom-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bom-Test
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SVProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  
  # Used for drop down
  pod 'DropDown'
  
end
